### ISSUE TITLE
Hi "Internal Server Error"

### ISSUE THREAD

**Issue by prashant7july** [yzhong52/microservices-demo#1]
Hi,

I have follow you step in my node project but still facing an Issues "Internal Server Error", Please help me

https://github.com/prashant7july/k8s/tree/master/node/exercise06/plans-service

**Comment by yzhong52** [comment]
Hello Prashant,

Sorry, it was hard to tell what's you did differently by just looking at your repo. I suggest cloning and trying on this branch directly:

https://github.com/yzhong52/microservices-demo/tree/starter

and comment back each step, each command that you run.
